#!/bin/sh
sleep 4

cd ~
# check for duplicate terminals
#if [ -e check ]; then
# rm -rf check 
#else

# lxde
#----------------------------------------------------------------------------------------
pcmanfm --set-wallpaper wall.jpg
echo '@xterm -geometry 40x4-250+0 -e ~/.steam-wine' >> ~/.config/lxsession/LXDE/autostart
echo '@xterm -geometry 40x4-0+0 -e ~/.steam-linux' >> ~/.config/lxsession/LXDE/autostart
echo '@xterm -geometry 73x31-0-25 -e ./utils' >> ~/.config/lxsession/LXDE/autostart
#----------------------------------------------------------------------------------------

# steam-linux
sudo mount -a
sudo su steam -c steam-install

# steam-wine
fetch https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe
wine SteamSetup.exe /S
wine ~/.wine/drive_c/Program\ Files/Steam/Steam.exe /S

# graphics
drv=`cat /etc/rc.conf | grep kld_list | cut -d '"' -f2`
case "$drv" in
 /boot/modules/amdgpu.ko)
 echo 'Detected amdgpu'
sudo su root -c 'cat << EOF > /usr/local/etc/X11/xorg.conf.d/xorg.conf
#Section "Device"
#        Identifier "Card0"
#        Driver     "amdgpu"
#EndSection
EOF'
 ;;
 /boot/modules/i915kms.ko)
 echo 'Detected i915kms'
sudo su root -c 'cat << EOF > /usr/local/etc/X11/xorg.conf.d/xorg.conf
#Section "Device"
#        Identifier "Card0"
#        Driver     "intel"
#EndSection
EOF'
 ;;
 /boot/modules/radeonkms.ko)
 echo 'Detected radeonkms'
sudo su root -c 'cat << EOF > /usr/local/etc/X11/xorg.conf.d/xorg.conf
#Section "Device"
#        Identifier "Card0"
#        Driver     "radeonkms"
#EndSection
EOF'
 ;;
 nvidia-modeset)
 echo 'Detected nvidia-modeset'
sudo su root -c 'cat << EOF > /usr/local/etc/X11/xorg.conf.d/xorg.conf 
#Section "Device"
#        Identifier "NVIDIA Card"
#        VendorName "NVIDIA Corporation"
#        Driver "nvidia"
#EndSection
EOF'
 ;;
 *)
 echo 'Detected vesa'
 ;;
esac

# create Readme.txt
cat << EOF > ~/Desktop/Readme.txt
HOW TO INSTALL GAMES
1. Found your favorite steam game and remember ID (in browsers link)
2. Open terminal and enter follow code:
wine ~/.wine/drive_c/Program\ Files/Steam/steam.exe steam://install/630
Where 630 - ID of steam game
P.S. If linux-steam-utils work, you may add games to libroray game. Just click "Play" but not install game, open wine-based steam and you see this game.

HOW TO CONFIGURE WINE [IT IS NOT NECESSARY]
winetricks dotnet40 arial vcrun2015 xna40
winetricks win10
winecfg
#in Graphics section uncheck: allow window manager to decorate windows

HOW TO CREATE WINE-PREFIX 
# for preinstall i386-wine
env WINEPREFIX=/home/<user>/.wine-test wine winecfg
# for test exprimental proton (you must login special user steamdev)
env WINEPREFIX=/home/steamdev/.wine-test /opt/steam-utils/bin/lsu-wine-env wine winecfg
env WINEPREFIX=/home/steamdev/.wine-test /opt/steam-utils/bin/lsu-wine-env wine64 winecfg

HOW TO BACKUP [ZFS method]
1. Create snapshot
sudo zfs snapshot zroot/usr/home@backup
2. Restore snapshot
sudo zfs rollback zroot/usr/home@backup
3. Destroy snapshot
sudo zfs destroy zroot/usr/home@backup

HOW TO CHANGE SCREEN RESOLUTION 
1. open file xorg.conf and add section 
sudo ee /usr/local/etc/X11/xorg.conf.d/xorg.conf
...
Section "Screen"
        Identifier "Screen0"
        Device     "Card0"
        Monitor    "Monitor0"
        SubSection "Display"
                Viewport   0 0
                Depth     24
                Modes     "1920x1080"
        EndSubSection
EndSection

2. For example resolution  1920x1080, you may use other 

3. Press ESC and leave editor with save changes

P.S.
For more information see 
Youtube: SteamBSD [https://www.youtube.com/channel/UC8wwRY8yGWiJ-bIQlK0wvUA]
Site: http://steambsd.epizy.com
All quastions send to email: light.progres@gmail.com
Thank you. 
EOF

mv ~/autoconfig ~/.autoconfig
#sudo shutdown -r now
#sudo reboot 
#fi

