#!/bin/sh

sleep 4
cd ~

############################################
### Desktop customization                ###
############################################
# create Readme.txt
mv deskreadme Desktop/Readme.txt
# change wallpaper
pcmanfm --set-wallpaper wall.jpg
# autostart
echo '@xterm -geometry 40x4-250+0 -e ~/.steam-wine' >> ~/.config/lxsession/LXDE/autostart
echo '@xterm -geometry 40x4-0+0 -e ~/.steam-linux' >> ~/.config/lxsession/LXDE/autostart
echo '@xterm -geometry 73x31-0-25 -e ./utils' >> ~/.config/lxsession/LXDE/autostart
# steam-linux
#sudo mount -a
sudo su steam -c steam-install
# steam-wine
fetch https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe
wine SteamSetup.exe /S
wine ~/.wine/drive_c/Program\ Files/Steam/Steam.exe /S

mv ~/autoconfig ~/.autoconfig
sudo reboot 


