#!/bin/sh

echo '==> Start boost PC...'
sleep 2

sudo killall -HUP wine
sudo killall -HUP wine.bin
sudo killall -HUP chrome
sudo killall -HUP compton
sudo killall -HUP cairo-clock

sudo service syslogd stop
sudo service cleartmp stop

sudo service lpd stop
sudo service cupsd stop
sudo service cups_browsed stop

sudo kldunload ext2fs
sudo kldunload udf

sudo sysctl kern.vt.enable_bell=0
sudo sysctl hw.syscons.bell=0

sleep 2
