#!/bin/sh
neofetch --color_blocks off --refresh_rate on --ascii .logo --config .config-neofetch
S0='       The morning is very cold!       '
S1='Developer: '
S2=`echo "Dmitry V"`
printf "\033[1;34m${S0} \033[1;31m${S1}\033[0;m${S2}\n"
C0='       Try commands: ctris, dgen       '
C1='Smile: '
C2=`echo '¯\\\\(°_o)/¯'`
printf "\033[1;34m${C0} \033[1;31m${C1}\033[0;m${C2}\n"
echo ' '
/usr/local/bin/bash
