#!/bin/sh
neofetch --color_blocks off --refresh_rate on --ascii .logo --config .config-neofetch
S0='       Good night and good luck!       '
S1='Telegram Group: '
S2=`echo 'https://t.me/steambsd'`
printf "\033[1;34m${S0} \033[1;31m${S1}\033[0;m${S2}\n"
C0='               ¯\\\(°_o)/¯               '
C1='$: '
C2=`echo 'https://www.donationalerts.com/r/steambsd'`
printf "\033[1;34m${C0} \033[1;31m${C1}\033[0;m${C2}\n"
echo ' '
/usr/local/bin/bash
