#!/bin/sh

############################################
### Desktop customization                ###
############################################
sleep 2
printf '%s\n' /desktop-/a 'background\filelist=/usr/local/share/wallpapers/wall.jpg' . w q | ex -s /root/.config/lumina-desktop/desktopsettings.conf >> /dev/null 2>&1
sed -i '' '/rssreader/d' /root/.config/lumina-desktop/desktopsettings.conf >> /dev/null 2>&1

cat << EOF > /root/Desktop/Chrome.desktop
[Desktop Entry]
Name=Chrome
Exec=chrome --no-sandbox --force-dark-mode --window-size=640,760 --window-position=640,0 https://store.steampowered.com/
StartupNotify=true
Type=Application
Icon=/usr/local/share/pixmaps/yrchrome.png
EOF
cat << EOF > /root/Desktop/Installer.desktop 
[Desktop Entry]
Name=Installer
Exec=xterm -geometry 100x50-0-100 -e bsdinstall
Type=Application
StartupNotify=true
Icon=/usr/local/share/pixmaps/yinstall.png
EOF

############################################
### Readme.txt                           ###
############################################
cat << EOF > /root/Desktop/Readme


--- SteamBSD © is FREE operating system.
Site: https://lpros.blogspot.com
Github (inet): https://github.com/steambsd/os
Telegram: https://t.me/steambsd

--- Help to SteamBSD project
MIR: 2202 2068 2683 8075
YMoney: https://yoomoney.ru/to/4100117613550064
DAlerts: https://www.donationalerts.com/r/steambsd

--- Help to SteamBSD from BANK
Beneficiary account: 40817810203002314378
Beneficiary Bank: SBERBANK
BIK: 040813608

--- Help to SteamBSD (CONTACT METHOD)
Link: https://www.contact-sys.com/
Name: VYSOCHIN DMITRIY VALENTINOVICH
My Phone: +7-963-810-26-31

--- Help the SteamBSD project with cryptocurrencies
DonatePay: https://new.donatepay.ru/@972255
Green WT (BTC): 3GP3TM46FbczJL4YrGrFnspfH5RzXY7soo
MetaMask (ETH): 0x114aB181D26807BdA2A7763e1e37c4D2c438C066

--- Other information
Skype: Progres Light
Email: steambsd@gmail.com
RSS: https://lpros.blogspot.com/feeds/posts/default
EOF

############################################
### Final                                ###
############################################
mv ~/reconfig-mini ~/.reconfig-mini

echo '################################################'
echo '###              Recommendations             ###'
echo '################################################'
echo 'If LAN not work, run "bsdconfig networking"'
echo 'Or use pc-networkmanager (right-bottom tray icon)'
echo 'Also run shortcut installer to install from GUI.'
echo 'Just enter your parametrs...'
echo '-------------------------------------'
printf "\033[1;31mReconfig was successful!\033[0;m\n"
printf "\033[1;34mThis is mini installation.\033[0;m\n"
echo '-------------------------------------'
sleep 10
