#!/bin/sh
sleep 2
cd ~
echo "Start customization for user $USER"

############################################
### Filesystem                           ###
############################################
# fstab and mount
sudo su root -c "echo 'linprocfs       /compat/linux/proc      linprocfs rw           0 0' >> /etc/fstab"
sudo su root -c "echo 'linsysfs        /compat/linux/sys       linsysfs  rw           0 0' >> /etc/fstab"
sudo su root -c "echo 'tmpfs           /compat/linux/dev/shm   tmpfs     rw,mode=1777 0 0' >> /etc/fstab"
sudo su root -c "echo 'fdesc           /dev/fd                 fdescfs   rw           0 0' >> /etc/fstab"
sudo mount -a

sleep 15
############################################
### Desktop customization                ###
############################################

#shortcut
cat << EOF > Desktop/SWine.desktop 
[Desktop Entry]
Name=SWine
Exec=wine .wine/drive_c/Program\ Files/Steam/steam.exe steam://open/minigameslist -no-browser
Type=Application
StartupNotify=true
Icon=/usr/local/share/pixmaps/zico-wine.png
EOF
cat << EOF > Desktop/SLinux.desktop 
[Desktop Entry]
Name=SLinux
Exec=steam
Type=Application
StartupNotify=true
Icon=/usr/local/share/pixmaps/zico-linux.png
EOF
cat << EOF > Desktop/SYSet.desktop 
[Desktop Entry]
Name=SYSet
Exec=xterm -geometry 73x31-0-25 -e ./.utils &
Type=Application
StartupNotify=true
Icon=/usr/local/share/pixmaps/ysettings.png
EOF
cat << EOF > Desktop/Info.desktop 
[Desktop Entry]
Name=Info
Exec=lxterminal -e ./.info &
Type=Application
StartupNotify=true
Icon=/usr/local/share/pixmaps/mini.xterm_48x48.xpm
EOF

#lxde
#pcmanfm --set-wallpaper wall.jpg
pcmanfm --set-wallpaper /usr/local/share/wallpapers/wall.jpg >> /dev/null 2>&1

#lxqt
#pcmanfm-qt --set-wallpaper wall.jpg
pcmanfm-qt --set-wallpaper /usr/local/share/wallpapers/wall.jpg >> /dev/null 2>&1
#sudo su root -c "sed -i '' 's/DisableQuotes=false/DisableQuotes=true/g' /home/$USER/.config/lxqt/session.conf"
#sudo su root -c "echo 'window_manager=openbox' >> /home/$USER/.config/lxqt/session.conf"

#lumina
sudo su root -c "sed -i '' 's/hidepanel=false/hidepanel=true/g' /home/$USER/.config/lumina-desktop/desktopsettings.conf" >> /dev/null 2>&1
sudo su root -c "sed -i '' 's/DisableQuotes=false/DisableQuotes=true/g' /home/$USER/.config/lumina-desktop/sessionsettings.conf" >> /dev/null 2>&1
#sudo su root -c "printf '%s\n' /desktop-default/a 'background\filelist=/usr/local/share/wallpapers/wall.jpg' . w q | ex -s /home/$USER/.config/lumina-desktop/desktopsettings.conf" >> /dev/null 2>&1
sudo su root -c "printf '%s\n' /desktop-DP-0/a 'background\filelist=/usr/local/share/wallpapers/wall.jpg' . w q | ex -s /home/$USER/.config/lumina-desktop/desktopsettings.conf" >> /dev/null 2>&1
#sudo su root -c "sed -i '' 's/pluginlist=rssreader---default.1/pluginlist=@Invalid()/g' /home/$USER/.config/lumina-desktop/desktopsettings.conf" >> /dev/null 2>&1
#sudo su root -c "sed -i '' 's/pluginlist=rssreader---DP-0.1/pluginlist=@Invalid()/g' /home/$USER/.config/lumina-desktop/desktopsettings.conf" >> /dev/null 2>&1
sudo su root -c "sed -i '' 's/currentfeeds=/currentfeeds=https:\/\/lpros.blogspot.com\/feeds\/posts\/default/g' /home/$USER/.config/lumina-desktop/pluginsettings/desktopsettings.conf" >> /dev/null 2>&1

#plasma
sed -i '' '/Image=file/d' /home/$USER/.config/plasma-org.kde.plasma.desktop-appletsrc >> /dev/null 2>&1
printf '%s\n' /Wallpaper/a 'Image=file:///usr/local/share/wallpapers/wall.jpg' . w q | ex -s .config/plasma-org.kde.plasma.desktop-appletsrc >> /dev/null 2>&1
( kquitapp5 plasmashell || killall plasmashell && kstart5 plasmashell ) >> /dev/null 2>&1

# relay
echo 'Please, wait...'
sleep 400
rm Desktop/Steam.desktop >> /dev/null 2>&1
############################################
### Readme.txt                           ###
############################################
cat << EOF > ~/Desktop/Readme
ATTENTION!
1. Proton is experemental version, it may not work.
2. If you have problem - try reboot PC.

HOW TO INSTALL WINE GAMES
1. Found your favorite steam game and remember ID (in browsers link)
2. Open terminal and enter follow code:
wine ~/.wine/drive_c/Program\ Files/Steam/steam.exe steam://install/630
Where 630 - ID of steam game
P.S. If linux-steam-utils work, you may add games to libroray game. 
Just click "Play" but not install game, open wine-based steam and you see this game.

HOW TO CREATE WINE-PREFIX 
# for preinstall i386-wine
env WINEPREFIX=/home/admin/.wine-test wine winecfg
# for test exprimental proton (you must login special user steamdev)
env WINEPREFIX=/home/steamdev/.wine-test /opt/steam-utils/bin/lsu-wine-env wine winecfg
env WINEPREFIX=/home/steamdev/.wine-test /opt/steam-utils/bin/lsu-wine-env wine64 winecfg

HOW TO BACKUP [ZFS method]
See utils

HOW TO CHANGE SCREEN RESOLUTION 
1. Open file xorg.conf and add section 
sudo ee /usr/local/etc/X11/xorg.conf.d/xorg.conf
Section "Screen"
        Identifier "Screen0"
        Device     "Card0"
        Monitor    "Monitor0"
        SubSection "Display"
                Viewport   0 0
                Depth     24
                Modes     "1920x1080"
        EndSubSection
EndSection
2. Press ESC, "a" and "a" to save and leave editor

P.S.
Youtube: SteamBSD (https://www.youtube.com/channel/UC8wwRY8yGWiJ-bIQlK0wvUA)
Site: http://steambsd.epizy.com
All quastions send to email: light.progres@gmail.com
EOF


############################################
### Plugins for Steam                    ###
############################################
#read ans
#python --version
#pip --version
#pip install steam-acolyte
#echo 'export PATH=$PATH:.local/bin/' >> ~/.bashrc
#export PATH=$PATH:.local/bin/
#xterm -geometry 40x4-500+0 -e steam-acolyte &


############################################
### Final                                ###
############################################
mv ~/reconfig ~/.reconfig
echo '################################################'
echo '###      System installed successfully!      ###'
echo '################################################'
echo ''
echo 'It is recommended to wait for Steam updates.'
echo 'You may reboot later. Just enjoy!!!'
echo ''
echo '-------------------------------------'
echo -n 'Do you want to reboot PC now? (yes, no): '
read ans
case "$ans" in
[Yy]|[Yy][Ee][Ss])
 echo "OK. Good bye."
 sudo reboot
 ;;
[Nn]|[Nn][Oo])
 echo "OK. Go on."
 ;;
*)
 echo "Error. Please, type yes or no."
 ;;
esac
