#!/bin/sh

############################################
### Desktop customization                ###
############################################
sleep 2
printf '%s\n' /desktop-/a 'background\filelist=/usr/local/share/wallpapers/wall.jpg' . w q | ex -s /root/.config/lumina-desktop/desktopsettings.conf >> /dev/null 2>&1
sed -i '' 's/pluginlist/ /g' /root/.config/lumina-desktop/desktopsettings.conf >> /dev/null 2>&1

cat << EOF > /root/Desktop/Chrome.desktop
[Desktop Entry]
Name=Chrome
Exec=chrome --no-sandbox --force-dark-mode --window-size=640,760 --window-position=640,0 https://store.steampowered.com/
StartupNotify=true
Type=Application
Icon=/usr/local/share/pixmaps/yrchrome.png
EOF
cat << EOF > /root/Desktop/Installer.desktop 
[Desktop Entry]
Name=Installer
Exec=xterm -geometry 100x50-0-100 -e bsdinstall
Type=Application
StartupNotify=true
Icon=/usr/local/share/pixmaps/yinstall.png
EOF

############################################
### Readme.txt                           ###
############################################
cat << EOF > /root/Desktop/Readme

--- SteamBSD © is FREE operating system.
Site (ISO/IMG): https://lpros.blogspot.com
Github (inet): https://github.com/steambsd/os
Email: steambsd@gmail.com

--- Help to SteamBSD project
Mastercard: 5336 6903 9850 8962
Yoomoney (Yandex.Money): 4100 1172 5027 6133
DAlerts: https://www.donationalerts.com/r/steambsd
EOF

############################################
### Final                                ###
############################################
mv ~/reconfig-mini ~/.reconfig-mini

echo '################################################'
echo '###              Recommendations             ###'
echo '################################################'
echo 'If LAN not work, run "doas bsdconfig networking"'
echo 'Or use pc-networkmanager (right-bottom tray icon)'
echo 'Also run shortcut installer to install from GUI.'
echo 'Just enter your parametrs...'
echo '-------------------------------------'
printf "\033[1;31mReconfig was successful!\033[0;m\n"
printf "\033[1;34mThis is mini installation.\033[0;m\n"
echo '-------------------------------------'
sleep 20
