#!/bin/sh
############################################
###          SIMPLE INSTALLATION         ###
###                 STEAM                ###   
###              ON FREEBSD              ###
############   set permission   ############
chmod +x autoconfig
chmod +x steam-linux
chmod +x steam-wine
chmod +x utils

############################################
### Variables                            ###
############################################
# user with wheel group
AZER=$1
# choose driver for your PC, it may be: 
# nvidia, amdgpu, radeon, intel or vesa
DRIV=$2
# desktop environment 
DENV=$3
# version
VERS=`uname -r | cut -d'-' -f1`
#VERS='12.0' #not tested
#VERS='12.1' #rebuild drm
#VERS='12.2' #without drm

############################################
### Function                             ###
############################################
# package type installation (local or inet)
pli()
{
if [ -d All ]; then
pkg add All/$1-*
else
pkg ins -y $1
fi
}

############################################
### Bugs                                 ###
############################################
# drm-kmod not work on FreeBSD 12.2
#if [ $DRIV != 'nvidia' ]; then DRIV='vesa'; fi

############################################
### Check system                         ###
############################################
# blank arguments
case "$#" in
0)
 # default: user - admin, driver - nvidia
 AZER='admin'
 pw useradd $AZER -m -b /usr/home -G wheel; echo 0000 | pw usermod $AZER -h0
 DRIV='nvidia'
 DENV='lxqt'
 ;;
3)
 # add if not exist
 pw usershow $AZER || chk=1
 if [ $chk = 1 ]; then
  echo "Create user $AZER"
  pw useradd $AZER -m
  echo '0000' | pw usermod $AZER -h0
 fi
 # try to wheel
 pw usermod $AZER -G wheel
 ;;
*)
 echo "Error. Please, type three arguments."
 echo "Usage: $0 [your_user] [video_driver] [your_desktop]"
 exit 0
 ;;
esac

############################################
### Tuning                               ###
############################################
# /boot/loader.conf
sysrc -f /boot/loader.conf autoboot_delay=2
sysrc -f /boot/loader.conf beastie_disable=YES
# /etc/sysctl.conf
echo 'kern.coredump=0' >> /etc/sysctl.conf
sysctl kern.coredump=0
# /etc/rc.conf
sysrc clear_tmp_enable=YES
sysrc sendmail_enable=NO
sysrc moused_enable=NO
sysrc sshd_enable=NO

############################################
### Update                               ###
############################################
if [ -d All ]; then
tar xf All/pkg-* -s ",/.*/,,g" "*/pkg-static"
./pkg-static add All/pkg-*
else
# system
env PAGER=cat freebsd-update fetch
freebsd-update install
# pkg
env ASSUME_ALWAYS_YES=YES pkg bootstrap
env ASSUME_ALWAYS_YES=YES pkg update -f
fi

############################################
### Prepare                              ###
############################################
# for user privilegies
pli sudo
pli bash
echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /usr/local/etc/sudoers
pw usermod $AZER -s /usr/local/bin/bash
# user for steam
pw useradd steam -m
pw usermod steam -s /usr/local/bin/bash
# user for steam development
pw useradd steamdev -m
pw usermod steamdev -s /usr/local/bin/bash
# linux
sysrc linux_enable=YES
sysrc linux64_enable=YES
kldload linux
kldload linux64

############################################
### Packages                             ###
############################################
# packages for WM
pli xorg
pli slim
# packages for wine
pli i386-wine
pli winetricks
pli wine-mono
pli wine-gecko
# packages for linux
pli linux-steam-utils
# packages for comfort
pli leafpad
pli lxterminal
pli chromium
pli vlc
pli simplescreenrecorder
# extended
#pli qt5

############################################
### Driver                               ###
############################################
case "$DRIV" in
 nvidia)
pli nvidia-driver
pli linux-nvidia-libs
pli nvidia-settings
sysrc kld_list+="/boot/modules/nvidia-modeset.ko"
kldload /boot/modules/nvidia-modeset.ko
cat << EOF > /usr/local/etc/X11/xorg.conf.d/xorg.conf 
Section "Device"
        Identifier "NV Card"
        Driver "nvidia"
EndSection
EOF
 ;;
 nvidia-390)
pli nvidia-driver-390
pli linux-nvidia-libs-390
pli nvidia-settings
sysrc kld_list+="/boot/modules/nvidia-modeset.ko"
kldload /boot/modules/nvidia-modeset.ko
cat << EOF > /usr/local/etc/X11/xorg.conf.d/xorg.conf 
Section "Device"
        Identifier "NV Card"
        Driver "nvidia"
EndSection
EOF
 ;;
 nvidia-340)
pli nvidia-driver-340
pli linux-nvidia-libs-340
pli nvidia-settings
sysrc kld_list+="/boot/modules/nvidia-modeset.ko"
kldload /boot/modules/nvidia-modeset.ko
cat << EOF > /usr/local/etc/X11/xorg.conf.d/xorg.conf 
Section "Device"
        Identifier "NV Card"
        Driver "nvidia"
EndSection
EOF
 ;;
 nvidia-304)
pli nvidia-driver-304
pli linux-nvidia-libs-304
pli nvidia-settings
sysrc kld_list+="/boot/modules/nvidia-modeset.ko"
kldload /boot/modules/nvidia-modeset.ko
cat << EOF > /usr/local/etc/X11/xorg.conf.d/xorg.conf 
Section "Device"
        Identifier "NV Card"
        Driver "nvidia"
EndSection
EOF
 ;;
 amdgpu)
pli drm-kmod
pw groupmod video -m $AZER
pw groupmod video -m steam
pw groupmod video -m steamdev
pli xf86-video-amdgpu
sysrc kld_list+="/boot/modules/amdgpu.ko"
kldload /boot/modules/amdgpu.ko
#cat << EOF > /usr/local/etc/X11/xorg.conf.d/xorg.conf 
#Section "Device"
#        Identifier "Card0"
#        Driver     "amdgpu"
#EndSection
#EOF
 ;;
  radeon)
pli drm-kmod
pw groupmod video -m $AZER
pw groupmod video -m steam
pw groupmod video -m steamdev
pli xf86-video-ati
sysrc kld_list+="/boot/modules/radeonkms.ko"
kldload /boot/modules/radeonkms.ko
#cat << EOF > /usr/local/etc/X11/xorg.conf.d/xorg.conf 
#Section "Device"
#        Identifier "Card0"
#        Driver     "radeonkms"
#EndSection
#EOF
 ;;
 intel)
pli drm-kmod
pw groupmod video -m $AZER
pw groupmod video -m steam
pw groupmod video -m steamdev
pli xf86-video-intel
sysrc kld_list+="/boot/modules/i915kms.ko"
kldload /boot/modules/i915kms.ko
#cat << EOF > /usr/local/etc/X11/xorg.conf.d/xorg.conf 
#Section "Device"
#        Identifier "Card0"
#        Driver     "intel"
#EndSection
#EOF
 ;;
 *)
#cat << EOF > /usr/local/etc/X11/xorg.conf.d/xorg.conf 
# Section "Device"
#    Identifier    "Card0"
#    Driver        "vesa"
# EndSection 
#EOF
 ;;
esac

case "$VERS" in
 12.0)
  #cd /usr/ports/graphics/drm-kmod && make BATCH=yes deinstall build install clean 
 ;;
 12.1)
  #fetch https://download.freebsd.org/ftp/releases/amd64/12.1-RELEASE/base.txz
  #fetch https://download.freebsd.org/ftp/releases/amd64/12.1-RELEASE/lib32.txz
  #tar -xvf base.txz -C /data/jails/basejail && tar -xvf lib32.txz -C /data/jails/basejail
  #rm -rf base.txz && rm -rf lib32.txz
  svnlite checkout http://svn.freebsd.org/base/releng/12.1/ /usr/src
  fetch https://github.com/FreeBSDDesktop/kms-drm/archive/drm-v5.0-fbsd12.1.zip
  unzip drm-v5.0-fbsd12.1.zip 
  mv kms-drm-drm-v5.0-fbsd12.1 kms-drm
  cd kms-drm
  make
  make install
  rm -rf kms-drm
  rm -rf drm-v5.0-fbsd12.1.zip
  #cp ./pci.ids /usr/local/share/pciids/pci.ids
 ;;
 12.2)
  sysrc kld_list-="/boot/modules/amdgpu.ko"
  sysrc kld_list-="/boot/modules/i915kms.ko"
  sysrc kld_list-="/boot/modules/radeonkms.ko"
  kldunload "/boot/modules/amdgpu.ko"
  kldunload "/boot/modules/i915kms.ko"
  kldunload "/boot/modules/radeonkms.ko"
 ;;
 13.0)
  echo 'Detect latest system'
  
 ;;
 *)
  echo -n 'Script is not intended for installation on this version of the system: '
  echo -n $VERS
  exit 0
 ;;
esac

############################################
### Files                                ###
############################################
# create documents folder
mkdir /home/$AZER/Documents
# copy steambsd scrips
cp autoconfig /home/$AZER/ 
cp steam-linux /home/$AZER/.steam-linux
cp steam-wine /home/$AZER/.steam-wine
cp utils /home/$AZER/.utils
cp wall.jpg /home/$AZER/

############################################
### Login manager                        ###
############################################
# slim customization
sysrc dbus_enable=YES
sysrc hald_enable=YES
sysrc slim_enable=YES
echo "default_user        $AZER" >> /usr/local/etc/slim.conf
echo 'auto_login          yes' >> /usr/local/etc/slim.conf
echo 'focus_password      yes' >> /usr/local/etc/slim.conf

############################################
### Desktop environment                  ###
############################################
# choose desktop
case "$DENV" in
kde)
pli plasma5-plasma
echo 'startplasma-x11' >> /home/$AZER/.xinitrc
 ;;
lumina)
pli lumina
echo 'start-lumina-desktop' >> /home/$AZER/.xinitrc
 ;;
lxqt)
pli lxqt
echo 'startlxqt' >> /home/$AZER/.xinitrc
 ;;
lxde)
pli lxde-meta
# start session
echo 'ck-launch-session dbus-launch --exit-with-session startlxde' >> /home/$AZER/.xinitrc
echo 'startlxde' >> /home/$AZER/.xinitrc
# file removal protection
cat << EOF >> /etc/crontab
@reboot root /bin/echo 'startlxde' > /home/$AZER/.xinitrc
EOF
# autostart
cat << EOF >> /usr/local/etc/xdg/lxsession/LXDE/autostart 
@xterm -geometry 50x15+0-25 -e ~/autoconfig
@xterm -geometry 40x4-250+0 -e ~/.steam-wine
@xterm -geometry 40x4-0+0 -e ~/.steam-linux
@xterm -geometry 73x31-0-25 -e ./.utils
EOF
 ;;
*)
 echo "Error. Unrecognized desktop."
 exit 0
 ;;
esac

# adding buttons
cat << EOF >> /usr/local/etc/polkit-1/rules.d/50-default.rules
polkit.addRule(function (action, subject) 
  if ((action.id == "org.freedesktop.consolekit.system.restart" ||
      action.id == "org.freedesktop.consolekit.system.stop")
      && subject.isInGroup("wheel")) {
    return polkit.Result.YES;
  }
});
EOF

# autostart
cat << EOF >> /usr/local/etc/xdg/autostart/utils.desktop 
[Desktop Entry]
Name=utils
Type=Application
Exec=xterm -geometry 73x31-0-25 -e ./.utils
Terminal=false
EOF
cat << EOF >> /usr/local/etc/xdg/autostart/steam-wine.desktop 
[Desktop Entry]
Name=steam-wine
Type=Application
Exec=xterm -geometry 40x4-250+0 -e ~/.steam-wine
Terminal=false
EOF
cat << EOF >> /usr/local/etc/xdg/autostart/steam-linux.desktop 
[Desktop Entry]
Name=steam-linux
Type=Application
Exec=xterm -geometry 40x4-0+0 -e ~/.steam-linux
Terminal=false
EOF

############################################
### Final stage                          ###
############################################
# set permission
chown -R $AZER:wheel /home/$AZER/
# startx
service dbus start
service hald start
service slim start
su $AZER -c 'startx'
