#!/bin/sh
############################################
### Simple installation Steam on FreeBSD ###
############################################
### Config
# choose driver for your PC, it may be: nvidia, amdgpu, radeon, intel or vesa (vesa for virtual machine)
DRIVER='vesa'
echo "We have DRIVER = $DRIVER"
# user with wheel group
AZER=`ls /home`
echo "We have USER = $AZER"
# update
env PAGER=cat freebsd-update fetch
freebsd-update install
env ASSUME_ALWAYS_YES=YES pkg bootstrap
env ASSUME_ALWAYS_YES=YES pkg update -f
# packages
pkg ins -y sudo bash
echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /usr/local/etc/sudoers
pw usermod $AZER -s /usr/local/bin/bash
pkg ins -y xorg
# linux
sysrc linux_enable="YES"
sysrc linux64_enable="YES"
kldload linux
kldload linux64
# tuning
echo 'kern.coredump=0' >> /etc/sysctl.conf
sysctl kern.coredump=0
# linux filesystem
echo 'linprocfs       /compat/linux/proc      linprocfs rw  0 0' >> /etc/fstab
echo 'linsysfs        /compat/linux/sys       linsysfs  rw  0 0' >> /etc/fstab
echo 'tmpfs           /compat/linux/dev/shm   tmpfs     rw,mode=1777 0 0' >> /etc/fstab
echo 'fdesc           /dev/fd                 fdescfs   rw  0 0' >> /etc/fstab
# prepare linux-steam
pkg ins linux-steam-utils
mount -a
pw useradd steam -m
su steam -c steam-install
# slim
pkg ins -y slim
sysrc dbus_enable="YES"
sysrc hald_enable="YES"
sysrc slim_enable="YES"
service dbus start
service hald start
service slim start
echo "default_user        $AZER" >> /usr/local/etc/slim.conf
echo "auto_login          yes" >> /usr/local/etc/slim.conf
echo 'focus_password      yes' >> /usr/local/etc/slim.conf
# lxde
pkg ins -y lxde-meta
echo 'ck-launch-session dbus-launch --exit-with-session startlxde' >> /home/$AZER/.xinitrc
echo 'startlxde' >> /home/$AZER/.xinitrc
cat << EOF >> /usr/local/etc/polkit-1/rules.d/50-default.rules
polkit.addRule(function (action, subject) {
  if ((action.id == "org.freedesktop.consolekit.system.restart" ||
      action.id == "org.freedesktop.consolekit.system.stop")
      && subject.isInGroup("wheel")) {
    return polkit.Result.YES;
  }
});
EOF
cat << EOF >> /etc/crontab
@reboot root /bin/echo 'startlxde' > /home/$AZER/.xinitrc
EOF

su $AZER -c 'startx'
