#!/bin/sh
############################################
### Simple installation Steam on FreeBSD ###
############################################
### Config
# choose driver for your PC, it may be: nvidia, amdgpu, radeon, intel or vesa (vesa for virtual machine)
DRIVER='vesa'
echo "We have DRIVER = $DRIVER"
# user with wheel group
AZER=`ls /home`
echo "We have USER = $AZER"
# update
env PAGER=cat freebsd-update fetch
freebsd-update install
env ASSUME_ALWAYS_YES=YES pkg bootstrap
env ASSUME_ALWAYS_YES=YES pkg update -f
# packages
pkg ins -y sudo bash
echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /usr/local/etc/sudoers
pw usermod $AZER -s /usr/local/bin/bash
pkg ins -y xorg
pkg ins -y slim
pkg ins -y lxde-meta
## packages for wine
pkg ins i386-wine
pkg ins winetricks
pkg ins wine-mono
pkg ins wine-gecko
# packages for linux
pkg ins linux-steam-utils
## packages for comfort
pkg ins -y leafpad
pkg ins -y chromium
pkg ins -y vlc
pkg ins -y simplescreenrecorder
# linux
sysrc linux_enable="YES"
sysrc linux64_enable="YES"
kldload linux
kldload linux64
# tuning
echo 'kern.coredump=0' >> /etc/sysctl.conf
sysctl kern.coredump=0
# slim
sysrc dbus_enable="YES"
sysrc hald_enable="YES"
sysrc slim_enable="YES"
service dbus start
service hald start
service slim start
echo "default_user        $AZER" >> /usr/local/etc/slim.conf
echo "auto_login          yes" >> /usr/local/etc/slim.conf
echo 'focus_password      yes' >> /usr/local/etc/slim.conf
# lxde
# ----------------------------------------------------------------------------------------
echo 'ck-launch-session dbus-launch --exit-with-session startlxde' >> /home/$AZER/.xinitrc
echo 'startlxde' >> /home/$AZER/.xinitrc
cat << EOF >> /usr/local/etc/polkit-1/rules.d/50-default.rules
polkit.addRule(function (action, subject) {
  if ((action.id == "org.freedesktop.consolekit.system.restart" ||
      action.id == "org.freedesktop.consolekit.system.stop")
      && subject.isInGroup("wheel")) {
    return polkit.Result.YES;
  }
});
EOF
cat << EOF >> /etc/crontab
@reboot root /bin/echo 'startlxde' > /home/$AZER/.xinitrc
EOF
#autostart
cat << EOF >> /usr/local/etc/xdg/lxsession/LXDE/autostart 
@lxterminal -e ~/autoconfig
EOF
# ----------------------------------------------------------------------------------------
# create files
echo '#!/bin/sh' > /home/$AZER/.steam-linux
echo 'sudo su steam -c steam' > /home/$AZER/.steam-linux
echo '#!/bin/sh' > /home/$AZER/.steam-wine
echo 'wine ~/.wine/drive_c/Program\ Files/Steam/steam.exe steam://open/minigameslist -no-browser' > /home/$AZER/.steam-wine
# copy files
cp autoconfig /home/${AZER}/ 
cp wall.jpg /home/${AZER}/
cp check /home/${AZER}/
cp utils /home/${AZER}/
# startx
su $AZER -c 'startx'


