#!/bin/sh
while true
do
echo 'steam-acolyte only text version'
if [ -d /home/steam/.steam ]; then
 sleep 5
 echo '-===SECOND ACCAUNT OF STEAM===-'
 echo 'Continue run steam (user steam)?'
 echo 'Press any key to proceed.'
 read ans
   read ans
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1 
   sleep 2
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   sudo su steam -c 'steam'
else
 sleep 60
 echo 'Install steam for user steam?'
 echo 'Press any key to proceed...'
   read ans
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1 
   sleep 2
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   sudo su steam -c 'steam-install &'
fi
read ans
done
