#!/bin/sh
sleep 4
if [ -d .wine ]; then
 echo '-===WINE VERSION OF STEAM===-'
 echo 'Continue run steam?'
 echo 'Press any key to proceed.'
 read ans
 wine ~/.wine/drive_c/Program\ Files/Steam/steam.exe steam://open/minigameslist -no-browser
 echo 'If you want reinstall steam-wine, please remove .wine and reboot pc'
else
 sudo winetricks --self-update
 winetricks -q 7zip
 sleep 2
 cd Desktop
 rm '7-Zip File Manager.desktop'
 rm '7-Zip Help.desktop'
 cd ..
 echo '-===WINE VERSION OF STEAM===-'
 echo 'Do you want install steam?'
 echo 'Press any key to install.'
 read ans
 fetch https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe
 wine SteamSetup.exe /S
 rm SteamSetup.exe
 wine ~/.wine/drive_c/Program\ Files/Steam/Steam.exe /S
 wine ~/.wine/drive_c/Program\ Files/Steam/steam.exe steam://open/minigameslist -no-browser
fi
read ans
