#!/bin/sh
sleep 4
if [ -d .wine ]; then
 echo '-===WINEPRO VERSION OF STEAM===-'
 echo 'Continue run steam?'
 echo 'Press any key to proceed.'
 read ans
 winepro ~/.winepro/drive_c/Program\ Files\ (x86)/Steam/steam.exe steam://open/minigameslist -no-browser
 echo 'If you want reinstall steam-winepro, please remove .wine and reboot pc'
else
 echo '-===WINEPRO VERSION OF STEAM===-'
 echo 'Do you want install steam?'
 echo 'Press any key to install.'
 read ans
 fetch https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe
 wine SteamSetup.exe /S
 rm SteamSetup.exe
 wine ~/.winepro/drive_c/Program\ Files/Steam/Steam.exe /S
 wine ~/.winepro/drive_c/Program\ Files/Steam/steam.exe steam://open/minigameslist -no-browser
fi
read ans
