#!/bin/sh
sleep 10
while true
do
if [ -d .steam ]; then
 kill -9 `cat /home/steam/.steam/steam.pid` > /dev/null 2>&1 
 sleep 2
 kill -9 `cat /home/steam/.steam/steam.pid` > /dev/null 2>&1
 /opt/steam-utils/bin/steam
 sleep 8
 echo 'If you want reinstall steam-compat, please remove .steam folder and reboot pc'
 echo 'Press any key to run steam again'
else
 kill -9 `cat /home/steam/.steam/steam.pid` > /dev/null 2>&1 
 sleep 2
 kill -9 `cat /home/steam/.steam/steam.pid` > /dev/null 2>&1
 rm -rf /home/steam/.steamdev
 sudo su steamdev -c /opt/steam-utils/bin/steam-install
 sudo mv /home/steamdev/.steam /home/$USER/.steam
 /opt/steam-utils/bin/lsu-pkg32 install -y wine-proton mesa-dri
 sudo chown -R $USER:wheel /home/$USER/.steam
 /opt/steam-utils/bin/steam
 sleep 8
 echo 'If you want reinstall steam-compat, please remove .steam folder and reboot pc'
 echo 'Press any key to run steam again'
fi
read ans
done
