#!/bin/sh
if [ -d .steam ]; then
 sleep 5
 .local/bin/steam-acolyte
else
 #sleep 1300
 echo 'I will be run after reboot'
 echo 'Please install proton before acolyte'
 echo '(first launch of SteamBSD)'
 #.local/bin/steam-acolyte
fi
read ans

