#!/bin/sh
sleep 4
if [ -d .wine ]; then
 wine ~/.wine/drive_c/Program\ Files/Steam/steam.exe steam://open/minigameslist -no-browser || echo 'remove .wine and reboot pc'
else
 sudo winetricks --self-update
 winetricks -q vcrun2015
 echo '-===WINE VERSION OF STEAM===-'
 echo 'Do you want install steam?'
 echo 'Press any key to install.'
 read ans
 fetch https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe
 wine SteamSetup.exe /S
 rm SteamSetup.exe
 wine ~/.wine/drive_c/Program\ Files/Steam/Steam.exe /S
 wine ~/.wine/drive_c/Program\ Files/Steam/steam.exe steam://open/minigameslist -no-browser
fi
read ans
