#!/bin/sh
sleep 4
while true
do
if [ -d .wine ]; then
 echo '-===WINE 32 VERSION OF STEAM===-'
 echo 'Continue run steam?'
 echo 'Press any key to proceed.'
 read ans
 wine ~/.wine/drive_c/Program\ Files/Steam/steam.exe steam://open/minigameslist -no-browser
 sleep 8
 echo 'If you want reinstall steam-wine, please remove .wine folder and reboot pc'
 echo 'Press any key to run steam again'
else
 sudo winetricks --self-update
 winetricks -q 7zip
 echo '-===WINE 32 VERSION OF STEAM===-'
 echo 'Do you want install steam?'
 echo 'Press any key to install.'
 read ans
 fetch https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe
 wine SteamSetup.exe /S
 rm SteamSetup.exe
 wine ~/.wine/drive_c/Program\ Files/Steam/Steam.exe /S
 wine ~/.wine/drive_c/Program\ Files/Steam/steam.exe steam://open/minigameslist -no-browser
fi
read ans
done

