#!/bin/sh
sleep 4
if [ -d .steam ]; then
 steam
else
 rm -rf /home/steam/.steam
 sudo su steam -c steam-install
 sudo mv /home/steam/.steam /home/$USER/.steam
 sudo chown -R $USER:wheel /home/$USER/.steam
 steam
fi
read ans
