#!/bin/sh
while true
do
echo 'steam-acolyte only text version'
if [ -d /home/steam/.steam ]; then
 sleep 5
 echo '-===SECOND ACCAUNT OF STEAM===-'
 echo 'Continue run steam (user steam)?'
 echo 'Press any key to proceed.'
 read ans
 kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1 
 sleep 2
 kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
 sudo su steam -c 'steam'
 sleep 8
 echo 'If you want reinstall steam, please remove /home/steam/.steam folder and reboot pc'
 echo 'Press any key to run steam again'
else
 sleep 60
 echo 'Install steam for user steam?'
 echo 'Press any key to proceed...'
 read ans
 kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1 
 sleep 2
 kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
 sudo su steam -c 'steam-install &'
 sudo su steam -c 'steam &'
 sleep 8
 echo 'If you want reinstall steam, please remove /home/steam/.steam folder and reboot pc'
 echo 'Press any key to run steam again'
fi
read ans
done
