#!/bin/sh
############################################
###          SIMPLE INSTALLATION         ###
###                 STEAM                ###   
###              ON FREEBSD              ###
############################################

############################################
### Variables                            ###
############################################
# user with wheel group
AZER=$1
# choose driver for your PC, it may be: 
# nvidia, amdgpu, radeon, intel or vesa (vm)
DRIV=$2

############################################
### Function                             ###
############################################
# check for type installation (local or inet)
pli()
{
if [ -d all ]; then
pkg add $1-*
else
pkg ins -y $1
fi
}

############################################
### Tuning                               ###
############################################
# /boot/loader.conf
sysrc -f /boot/loader.conf autoboot_delay=2
sysrc -f /boot/loader.conf beastie_disable=YES
# /etc/sysctl.conf
echo 'kern.coredump=0' >> /etc/sysctl.conf
sysctl kern.coredump=0
# /etc/rc.conf
sysrc clear_tmp_enable=YES
sysrc sendmail_enable=NO
sysrc moused_enable=NO
sysrc sshd_enable=YES

############################################
### Update                               ###
############################################
# system
env PAGER=cat freebsd-update fetch
freebsd-update install
# pkg
env ASSUME_ALWAYS_YES=YES pkg bootstrap
env ASSUME_ALWAYS_YES=YES pkg update -f

############################################
### Packages                             ###
############################################
# for user privilegies
pli sudo
pli bash
echo '%wheel ALL=(ALL) NOPASSWD: ALL' >> /usr/local/etc/sudoers
pw usermod $AZER -s /usr/local/bin/bash
# user for steam
pw useradd steam -m
pw usermod steam -s /usr/local/bin/bash
# linux
sysrc linux_enable=YES
sysrc linux64_enable=YES
kldload linux
kldload linux64

# packages for desktop environment
pli xorg
pli slim
pli lxde-meta
# packages for wine
pli i386-wine
pli winetricks
pli wine-mono
pli wine-gecko
# packages for linux
pli linux-steam-utils
# packages for comfort
#pli leafpad
#pli chromium
#pli vlc
#pli simplescreenrecorder

############################################
### Files                                ###
############################################
# create documents folder
mkdir /home/$AZER/Documents
# copy steambsd scrips
cp autoconfig /home/$AZER/ 
cp steam-linux /home/$AZER/.steam-linux
cp steam-wine /home/$AZER/.steam-wine
cp check /home/$AZER/
cp utils /home/$AZER/
cp wall.jpg /home/$AZER/

############################################
### Login manager                        ###
############################################
# slim customization
sysrc dbus_enable=YES
sysrc hald_enable=YES
sysrc slim_enable=YES
service dbus start
service hald start
service slim start
echo "default_user        $AZER" >> /usr/local/etc/slim.conf
echo "auto_login          yes" >> /usr/local/etc/slim.conf
echo 'focus_password      yes' >> /usr/local/etc/slim.conf

############################################
### Desktop environment                  ###
############################################
# start session
echo 'ck-launch-session dbus-launch --exit-with-session startlxde' >> /home/$AZER/.xinitrc
echo 'startlxde' >> /home/$AZER/.xinitrc
# adding power and reset buttons
cat << EOF >> /usr/local/etc/polkit-1/rules.d/50-default.rules
polkit.addRule(function (action, subject) {
  if ((action.id == "org.freedesktop.consolekit.system.restart" ||
      action.id == "org.freedesktop.consolekit.system.stop")
      && subject.isInGroup("wheel")) {
    return polkit.Result.YES;
  }
});
EOF
# file removal protection
cat << EOF >> /etc/crontab
@reboot root /bin/echo 'startlxde' > /home/$AZER/.xinitrc
EOF
# autostart
cat << EOF >> /usr/local/etc/xdg/lxsession/LXDE/autostart 
@lxterminal -e ~/autoconfig
EOF
# set permission
chown -R $AZER:wheel /home/$AZER/
# startx
su $AZER -c 'startx'


