#!/bin/sh
sleep 4
while true
do
if [ -f "/home/$USER/.winepro/drive_c/Program Files (x86)/Steam/steam.exe" ]; then
 echo '-===WINEPRO 32-64 VERSION OF STEAM===-'
 echo 'Continue run steam?'
 echo 'Press any key to proceed.'
 read ans
 cd '.winepro/drive_c/Program Files (x86)/Steam/'
 winepro steam.exe steam://open/minigameslist -no-browser
 cd ~
 sleep 8
 echo 'If you want reinstall steam-winepro, please remove .winepro folder and reboot pc'
 echo 'Press any key to run steam again'
else
 echo '-===WINEPRO 32-64 VERSION OF STEAM===-'
 echo 'Do you want install steam?'
 echo 'Press any key to install.'
 read ans
 fetch https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe
 winepro SteamSetup.exe /S
 rm SteamSetup.exe
 cd '.winepro/drive_c/Program Files (x86)/Steam/'
 winepro Steam.exe /S
 winepro steam.exe steam://open/minigameslist -no-browser
 cd ~

 echo '[Desktop Entry]' > Desktop/Steam64.desktop 
 echo 'Name=Steam64' >> Desktop/Steam64.desktop 
 echo 'Type=Application' >> Desktop/Steam64.desktop 
 echo 'Exec=steam-acolyte' >> Desktop/Steam64.desktop 
 echo 'Terminal=false' >> Desktop/Steam64.desktop
 echo 'Icon=/usr/local/share/pixmaps/ysteam.png' >> Desktop/Steam64.desktop 

fi
read ans
done

