#!/bin/sh

while :
do

clear

echo '### proton'
echo 'p1 - install proton 6.3'
echo 'p2 - install steam linux runtime - soldier'
echo 'p3 - select emulators/wine-proton in Settings -> Steam Play'
echo 'p4 - download simple free game (High Octane Drift)'
echo '### install steam game by id'
echo 'idc - install for steam-compat'
echo 'idw - install for steam-wine'
echo '### reinstall steam repo (you need reboot PC)'
echo 'ruc - update steam code '
echo 'rup - update steam code and proton libraries'
echo 'ras - restore autostart script for wine, winepro, compat'
echo 'mas - move autostart script for wine, winepro, compat'
echo '### add switch keyboard layout (temporary)'
echo 'sru - add russian switch alt-shift'
echo 'sgr - add greek switch alt-shift'
echo '### zfs snapshot'
echo 'zc - construct full snapshot of system'
echo 'zd - delete full snapshot of system'
echo 'zl - list snapshot of system'
echo 'zr - restore full snapshot of system'
echo '### resolution (you need reboot PC)'
echo '800 - add screen resolution 800x600 to xorg.conf'
echo '1366 - add screen resolution 1366x768 to xorg.conf'
echo '### video drivers, if full install (you need reboot PC)'
echo 'sta - switch to amdgpu'
echo 'stn - switch to nvidia'
echo 'sti - switch to intel'
echo '### system commands'
echo 'bd - boost down'
echo 'clr - clear system (small files, packages and etc)'
echo 'dsa - download and run Steam-Authenticator (in ~/Downloads folder)'
echo 'scr - restore xscreensaver'
echo 'ssh - enable SSH'
echo 'rbt - reboot PC'
echo 'sht - shutdown PC'
echo 'upd - update utils'
echo 'exit - close utils'
echo ''
echo -n 'Choose your number: '
 read ans
 case "$ans" in
 p1)
   ### install proton
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   sleep 2
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   lxterminal --geometry=40x4 -e /opt/steam-utils/bin/steam "steam://install/1580130" &
 ;;
 p2)
   ### install slrs
   killall -HUP lxterminal
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   sleep 2
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   lxterminal --geometry=40x4 -e /opt/steam-utils/bin/steam "steam://install/1391110" &
 ;;
 p3)
   ### select emulators/wine-proton in properties
   killall -HUP lxterminal
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1 
   sleep 2
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   /opt/steam-utils/bin/lsu-register-proton
   lxterminal --geometry=40x4 -e /opt/steam-utils/bin/steam &
 ;;
 p4)
   ### download simple game
   killall -HUP lxterminal
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   sleep 2
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   lxterminal --geometry=40x4 -e /opt/steam-utils/bin/steam "steam://install/457330" &
 ;;
 idc)
   ### install game for steam-compat
   lxterminal --geometry=40x4 -e sh .idc &
 ;;
 idw)
   ### install game for steam-wine
   lxterminal --geometry=40x4 -e sh .idw &
 ;;
 ruc)
   ### reinstall
   rm -rf .steam
   sudo rm -rf /opt/steam-utils
   cd /etc/ins
   sudo rm -rf linuxulator-steam-utils-master
   sudo rm -rf master.zip
   sudo fetch https://github.com/shkhln/linuxulator-steam-utils/archive/refs/heads/master.zip
   sudo unzip master.zip
   cd linuxulator-steam-utils-master
   sudo make
   sudo make install
 ;;
 rup)
   ### reinstall
   rm -rf .steam
   rm -rf .i386-wine-pkg
   sudo rm -rf /opt/steam-utils
   cd /etc/ins
   sudo rm -rf linuxulator-steam-utils-master
   sudo rm -rf master.zip
   sudo fetch https://github.com/shkhln/linuxulator-steam-utils/archive/refs/heads/master.zip
   sudo unzip master.zip
   cd linuxulator-steam-utils-master
   sudo make
   sudo make install
 ;;
 ras)
   ### restore
   mv ~/.steam-wine.save ~/.steam-wine
   mv ~/.steam-winepro.save ~/.steam-winepro
   mv ~/.steam-compat.save ~/.steam-compat
   #mv ~/.steam-acolyte.save ~/.steam-acolyte
 ;;
 mas)
   ### move
   mv ~/.steam-wine ~/.steam-wine.save
   mv ~/.steam-winepro ~/.steam-winepro.save
   mv ~/.steam-compat ~/.steam-compat.save
   #mv ~/.steam-acolyte ~/.steam-acolyte.save
 ;;
 rd)
   ### reinstall
   sudo su steamdev -c 'rm -rf .steam'
   sudo shutdown -r now
 ;;
 sru)
 setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle,grp_led:scroll"
 ;;
 sgr)
 setxkbmap -layout "us,gr" -option "grp:alt_shift_toggle,grp_led:scroll"
 ;;
 zc)
   ### create snapshot zroot
   sudo zfs snapshot -r zroot@backup
 ;;
 zd)
   ### delete snapshot zroot
   sudo zfs destroy -r zroot@backup
 ;;
 zl)
   ### list
   zfs list -t snapshot
   echo 'sleep 5 sec'
   sleep 5
 ;;
 zr)
   ### restore snapshot zroot
   sudo zfs rollback zroot@backup
   sudo zfs rollback zroot/ROOT@backup
   sudo zfs rollback zroot/ROOT/default@backup
   #sudo zfs rollback zroot/tmp@backup 
   sudo zfs rollback zroot/usr@backup
   sudo zfs rollback zroot/usr/home@backup
   sudo zfs rollback zroot/usr/ports@backup
   sudo zfs rollback zroot/usr/src@backup 
   sudo zfs rollback zroot/var@backup 
   sudo zfs rollback zroot/var/audit@backup
   sudo zfs rollback zroot/var/crash@backup
   sudo zfs rollback zroot/var/log@backup
   sudo zfs rollback zroot/var/mail@backup
   #sudo zfs rollback zroot/var/tmp@backup
 ;;
 800)
   ### add screen resolution 800x600
   sudo su root -c 'cat << EOF >> /usr/local/etc/X11/xorg.conf.d/xorg.conf

Section "Screen"
        Identifier "Screen0"
        Monitor    "Monitor0"
        SubSection "Display"
                Viewport   0 0
                Depth     24
                Modes     "800x600"
        EndSubSection
EndSection
EOF'
 ;;
 1366)
   ### add screen resolution 1366x768
   sudo su root -c 'cat << EOF >> /usr/local/etc/X11/xorg.conf.d/xorg.conf

Section "Screen"
        Identifier "Screen0"
        Monitor    "Monitor0"
        SubSection "Display"
                Viewport   0 0
                Depth     24
                Modes     "1366x768"
        EndSubSection
EndSection
EOF'
 ;;
 sta)
   ### switch to amdgpu
   sudo rm /usr/local/etc/X11/xorg.conf.d/corg.conf
   sudo sysrc kld_list+="/boot/modules/amdgpu.ko"
 ;;
 stn)
   ### switch to nvidia
   sudo cp /usr/local/etc/X11/xorg.conf.d/xorg.conf.nvidia /usr/local/etc/X11/xorg.conf.d/xorg.conf
   sudo sysrc kld_list+="/boot/modules/nvidia-modeset.ko"
 ;;
 sti)
   ### switch to intel
   sudo rm /usr/local/etc/X11/xorg.conf.d/corg.conf
   sudo sysrc kld_list+="/boot/modules/i915kms.ko"
 ;;
 bd)
   ### boost down
   compton &
   cairo-clock -w 200 -h 200 -x 200 -y 200 -s -t simple &
   sudo service syslogd start
   #sudo service cleartmp start
   sudo kldload ext2fs
   sudo kldload udf
   sudo sysctl kern.vt.enable_bell=1
   sudo sysctl hw.syscons.bell=1
   sleep 2
 ;;
 clr)
   ### clear
   sudo pkg clean -y
   rm -rf ~/.cache/winetricks/*
   find . -name DS_Store -type d -delete
   find . -name *.log -type f -delete
   sleep 2
 ;;
 dsa)
   ### download steam autenticator
   mkdir Downloads/SDA
   cd Downloads/SDA
   fetch https://github.com/Jessecar96/SteamDesktopAuthenticator/releases/download/1.0.10/SDA-1.0.10.zip
   unzip e SDA-1.0.10.zip
   rm SDA-1.0.10.zip
   lxterminal --geometry=40x4 -e wine 'Steam Authenticator.exe' &
   cd ~
 ;;
 scr)
   ### restore xscreensaver
   mv /usr/local/bin/xscreensaver.save /usr/local/bin/xscreensaver
 ;;
 ssh)
   ### ssh
   sudo sysrc sshd_enable=YES
   sudo service sshd start
 ;;
 rbt)
   ### reboot
   sudo shutdown -r now
 ;;
 sht)
   ### shutdown
   sudo shutdown -p now
 ;;
 upd)
   ### update utils
   fetch https://github.com/steambsd/os/archive/go.zip
   unzip go.zip
   mv os-go/utils .utils
   sudo chmod +x .utils
   rm -rf os-go
   rm go.zip
   xterm -geometry 73x41-0-25 -e ./.utils &
   sleep 2
   break
 ;;
 exit)
   echo 'Exit.'
   sleep 1
   break
 ;;
 *)
   echo "Error. Please, type number. Start again..."
 ;;
 esac
done
