#!/bin/sh

while :
do

clear

echo '### proton'
echo 'p1 - install proton 5.13'
echo 'p2 - install steam linux runtime - soldier'
echo 'p3 - select emulators/wine-proton in properties'
echo 'p4 - download simple game (High Octane Drift)'
echo 'p5 - reboot PC (optional)'
echo '### add switch keyboard layout (temporary)'
echo 'sru - add russian switch alt-shift'
echo 'sgr - add greek switch alt-shift'
echo '### zfs snapshot'
echo 'zc - construct full snapshot of system'
echo 'zd - delete full snapshot of system'
echo 'zl - list snapshot of system'
echo 'zr - restore full snapshot of system'
echo '### resolution'
echo '800 - add screen resolution 800x600 to xorg.conf'
echo '1366 - add screen resolution 1366x768 to xorg.conf'
echo '### system commands'
echo 'sht - shutdown pc'
echo 'rbt - reboot pc'
echo 'upd - update utils and reopen'
echo 'exit - close utils'
echo ''
echo -n 'Choose your number: '
 read ans
 case "$ans" in
 p1)
   ### install proton
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   sleep 2
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   lxterminal --geometry=40x4 -e /opt/steam-utils/bin/steam "steam://install/1420170" &
 ;;
 p2)
   ### install slrs
   killall -HUP lxterminal
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   sleep 2
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   lxterminal --geometry=40x4 -e /opt/steam-utils/bin/steam "steam://install/1391110" &
 ;;
 p3)
   ### select emulators/wine-proton in properties
   killall -HUP lxterminal
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1 
   sleep 2
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   /opt/steam-utils/bin/lsu-register-proton
   lxterminal --geometry=30x3 -e ~/.steam-linux &
 ;;
 p4)
   ### download simple game
   killall -HUP lxterminal
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   sleep 2
   kill -9 `cat ./.steam/steam.pid` > /dev/null 2>&1
   lxterminal --geometry=40x4 -e /opt/steam-utils/bin/steam "steam://install/457330" &
 ;;
 p5)
   ### reboot 
   sudo shutdown -r now
 ;;
 sru)
 setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle,grp_led:scroll"
 ;;
 sgr)
 setxkbmap -layout "us,gr" -option "grp:alt_shift_toggle,grp_led:scroll"
 ;;
 zc)
   ### create snapshot zroot
   sudo zfs snapshot -r zroot@backup
 ;;
 zd)
   ### delete snapshot zroot
   sudo zfs destroy -r zroot@backup
 ;;
 zl)
   ### list
   zfs list -t snapshot
   echo 'sleep 5 sec'
   sleep 5
 ;;
 zr)
   ### restore snapshot zroot
   sudo zfs rollback zroot@backup
   sudo zfs rollback zroot/ROOT@backup
   sudo zfs rollback zroot/ROOT/default@backup
   #sudo zfs rollback zroot/tmp@backup 
   sudo zfs rollback zroot/usr@backup
   sudo zfs rollback zroot/usr/home@backup
   sudo zfs rollback zroot/usr/ports@backup
   sudo zfs rollback zroot/usr/src@backup 
   sudo zfs rollback zroot/var@backup 
   sudo zfs rollback zroot/var/audit@backup
   sudo zfs rollback zroot/var/crash@backup
   sudo zfs rollback zroot/var/log@backup
   sudo zfs rollback zroot/var/mail@backup
   #sudo zfs rollback zroot/var/tmp@backup
 ;;
 800)
   ### add screen resolution 800x600
   sudo su root -c 'cat << EOF >> /usr/local/etc/X11/xorg.conf.d/xorg.conf

Section "Screen"
        Identifier "Screen0"
        Monitor    "Monitor0"
        SubSection "Display"
                Viewport   0 0
                Depth     24
                Modes     "800x600"
        EndSubSection
EndSection
EOF'
 ;;
  1366)
   ### add screen resolution 1366x768
   sudo su root -c 'cat << EOF >> /usr/local/etc/X11/xorg.conf.d/xorg.conf

Section "Screen"
        Identifier "Screen0"
        Monitor    "Monitor0"
        SubSection "Display"
                Viewport   0 0
                Depth     24
                Modes     "1366x768"
        EndSubSection
EndSection
EOF'
 ;;
  sht)
   ### help
   sudo shutdown -p now
 ;;
   rbt)
   ### reboot
   sudo shutdown -r now
 ;;
   upd)
   ### update utils
   fetch https://github.com/steambsd/os/archive/go.zip
   unzip go.zip
   mv os-go/utils .utils
   sudo chmod +x .utils
   rm -rf os-go
   rm go.zip
   xterm -geometry 73x41-0-25 -e ./.utils &
   sleep 2
   break
 ;;
 exit)
   echo 'Exit.'
   sleep 1
   break
 ;;
 *)
   echo "Error. Please, type number. Start again..."
 ;;
 esac
done
